name: testing of the code

on:
  push:
    branches:
      - main

jobs:
  code-format:
    runs-on: ubuntu-latest
    container: 
        image: Node:20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npm run format
